# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "hexy"
version = "0.1.0"
entrypoint = "/hexy.typ"
authors = ["gbrls"]
license = "Unlicense"
description = "A typesetting library for hexdumps and low level reverse engineering stuff for Typst "
homepage = "https://github.com/gbrls/hexy"
repository = "https://github.com/gbrls/hexy"
keywords = []
categories = []
disciplines = []
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]
